### ISSUE TITLE
Incorrect API Key provided...

### ISSUE THREAD

**Issue by Warface** [pescheckit/python-gpt-po#2]
I have create 2 API keys and none of them seems to work with this script. Anyone have that issue?

**Comment by pescheck-bram** [comment]
I dont have this issue did you try:

```
export OPENAI_API_KEY="" 
```

On the terminal? Or where do you supply the key ?

**Comment by pescheck-bram** [comment]
Test both ways to enter keys and they both work so I think this issue can be closed.
