### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by lumos675** [pescheckit/python-gpt-po#8]
gpt-po-translator --folder ./locales --lang ka --api_key 'CODE' --bulk --bulksize 40 --model "gpt-4o-mini" --folder-language --detail-lang "Georgian"

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:root:OpenAI connection validated successfully.
INFO:root:Discovered .po file: ./locales/en_GB.po
WARNING:root:Skipping .po file due to language mismatch: ./locales/en_GB.po

**Comment by pescheck-bram** [comment]
Can you deliver the po for us ?

**Comment by deweydb** [comment]
Just in case anyone else runs into this, in my case my po file was malformed. It was generated by a CRM and I guess the CRM had an issue. So if the above solution doesn't work for you, check to see if you po file has any blank sections like this:

```

#: some irrelevant comment about this translation string 
msgid ""
msgstr ""

```
